refactor: update string initialization to use macro TEN_STRING_INIT and update requirements

diff --git a/.github/workflows/build_linux_ubuntu2204.yml b/.github/workflows/build_linux_ubuntu2204.yml
--- a/.github/workflows/build_linux_ubuntu2204.yml
+++ b/.github/workflows/build_linux_ubuntu2204.yml
@@ -1,4 +1,4 @@
-name: Build - linux ubuntu2204
+name: Linux (Ubuntu 22.04)
 
 on:
   release:
@@ -14,11 +14,12 @@ on:
       - "!.github/workflows/build_linux_ubuntu2204.yml"
       - "**.md"
 
+concurrency:
+  group: linux-intel-ubuntu2204-${{ github.head_ref }}
+  cancel-in-progress: true
+
 jobs:
-  build-linux-ubuntu2204:
-    concurrency:
-      group: build-linux-ubuntu2204-${{ github.head_ref }}-${{ matrix.compiler }}-${{ matrix.build_type }}-${{ matrix.arch }}
-      cancel-in-progress: true
+  build-linux-intel-ubuntu2204:
     runs-on: ubuntu-latest
     strategy:
       matrix:
@@ -64,19 +65,6 @@ jobs:
           python3 tools/version/update_version_in_ten_framework.py
           python3 tools/version/check_version_in_ten_framework.py
 
-      - name: Set ulimit and sysctl
-        run: |
-          # Because there are concurrent test cases which involves many
-          # concurrent socket connections, we need to enlarge the maximum number
-          # of the opened file descriptor.
-          ulimit -n 102400
-
-          # Because there are concurrent test cases (in 'smoke' and
-          # 'integration') which will create many concurrent connections
-          # simutaneously, we increase the TCP listening backlog value to 8192.
-          sysctl -w net.core.somaxconn=8192
-        shell: bash
-
       - name: Install gcc-multilib and g++-multilib
         if: matrix.arch == 'x86'
         run: |
@@ -87,20 +75,25 @@ jobs:
         run: |
           export PATH=$(pwd)/core/ten_gn:$PATH
           echo $PATH
-          go env -w GOFLAGS="-buildvcs=false"
-          go1.20.12 download
-          rustup default nightly
+
+          if [ "${{ matrix.arch }}" = "x64" ]; then
+            go env -w GOFLAGS="-buildvcs=false"
+            go1.20.12 download
+            rustup default nightly
+          fi
 
           df -h .
 
           if [ "${{ matrix.arch }}" = "x86" ]; then
-            EXTRA_ARGS="is_clang=false ten_enable_ten_manager=false ten_manager_enable_frontend=false ten_rust_enable_tests=false ten_manager_enable_tests=false ten_enable_go_binding=false ten_enable_python_binding=false ten_enable_nodejs_binding=false ten_manager_enable_frontend=false ten_enable_integration_tests_prebuilt=false"
+            EXTRA_ARGS="is_clang=false ten_enable_ten_rust=false ten_enable_ten_manager=false ten_manager_enable_frontend=false ten_manager_enable_tests=false ten_enable_go_binding=false ten_enable_python_binding=false ten_enable_nodejs_binding=false ten_manager_enable_frontend=false ten_enable_integration_tests_prebuilt=false"
           else
             EXTRA_ARGS="is_clang=${{ matrix.compiler == 'gcc' && 'false' || 'true' }} log_level=1 enable_serialized_actions=true ten_enable_serialized_rust_action=true ten_rust_enable_gen_cargo_config=false ten_enable_cargo_clean=true ten_enable_go_lint=true ten_enable_rust_incremental_build=false ten_manager_enable_frontend=false ten_enable_integration_tests_prebuilt=false ten_enable_ffmpeg_extensions=true"
           fi
 
-          tgn gen linux x64 ${{ matrix.build_type }} -- $EXTRA_ARGS
-          tgn build linux x64 ${{ matrix.build_type }}
+          echo $EXTRA_ARGS
+
+          tgn gen linux ${{ matrix.arch }} ${{ matrix.build_type }} -- $EXTRA_ARGS
+          tgn build linux ${{ matrix.arch }} ${{ matrix.build_type }}
 
           df -h .
           tree -I 'gen|obj' out
@@ -110,7 +103,7 @@ jobs:
         run: |
           UPDATE_SUPPORTS_SCRIPT=$(pwd)/tools/supports/update_supports_in_manifest_json.py
 
-          cd out/linux/x64/ten_packages
+          cd out/linux/${{ matrix.arch }}/ten_packages
           ARRAY=(
             "system/ten_runtime"
             "system/ten_runtime_go"
@@ -126,36 +119,33 @@ jobs:
           df -h .
         shell: bash
 
-      - name: Upload tman
-        if: matrix.arch == 'x64'
-        uses: actions/upload-artifact@v4
-        with:
-          name: tman-linux-${{ matrix.compiler }}-${{ matrix.build_type }}-${{ matrix.arch }}
-          path: out/linux/x64/ten_manager/bin/tman
+        # Package the tests artifacts into a tar file while preserving file
+        # permissions.
+      - name: Package tests relevant artifacts preserving permissions
+        shell: bash
+        run: |
+          files=""
+          for item in tests ten_manager tgn_args.txt; do
+            if [ -e "out/linux/${{ matrix.arch }}/$item" ]; then
+              files="$files out/linux/${{ matrix.arch }}/$item"
+            fi
+          done
 
-      - name: Upload ten_packages
-        if: matrix.arch == 'x64'
+          if [ -n "$files" ]; then
+            tar -czvf tests-artifacts.tar.gz $files
+          fi
+
+      - name: Upload tests relevant artifacts
         uses: actions/upload-artifact@v4
         with:
-          name: ten_packages-linux-${{ matrix.compiler }}-${{ matrix.build_type }}-${{ matrix.arch }}
-          path: |
-            out/linux/x64/app/default_app_cpp
-            out/linux/x64/app/default_app_go
-            out/linux/x64/app/default_app_python
-            out/linux/x64/app/default_app_nodejs
-            out/linux/x64/ten_packages/system/ten_runtime
-            out/linux/x64/ten_packages/system/ten_runtime_go
-            out/linux/x64/ten_packages/system/ten_runtime_python
-            out/linux/x64/ten_packages/extension/default_extension_cpp
-            out/linux/x64/ten_packages/extension/default_extension_go
-            out/linux/x64/ten_packages/extension/default_extension_python
-            out/linux/x64/ten_packages/extension/default_async_extension_python
-            out/linux/x64/ten_packages/addon_loader/python_addon_loader
+          name: tests-artifacts-${{ matrix.compiler }}-${{ matrix.build_type }}-${{ matrix.arch }}
+          path: tests-artifacts.tar.gz
+          if-no-files-found: ignore
 
       - name: Package assets
         if: matrix.arch == 'x64' && startsWith(github.ref, 'refs/tags/')
         run: |
-          cd out/linux/x64
+          cd out/linux/${{ matrix.arch }}
           zip -vr tman-linux-${{ matrix.compiler }}-${{ matrix.build_type }}-${{ matrix.arch }}.zip ten_manager/bin/tman
           zip -vr ten_packages-linux-${{ matrix.compiler }}-${{ matrix.build_type }}-${{ matrix.arch }}.zip \
             app/default_app_cpp \
@@ -178,23 +168,23 @@ jobs:
         if: matrix.arch == 'x64' && startsWith(github.ref, 'refs/tags/')
         with:
           files: |
-            out/linux/x64/tman-linux-${{ matrix.compiler }}-${{ matrix.build_type }}-${{ matrix.arch }}.zip
-            out/linux/x64/ten_packages-linux-${{ matrix.compiler }}-${{ matrix.build_type }}-${{ matrix.arch }}.zip
+            out/linux/${{ matrix.arch }}/tman-linux-${{ matrix.compiler }}-${{ matrix.build_type }}-${{ matrix.arch }}.zip
+            out/linux/${{ matrix.arch }}/ten_packages-linux-${{ matrix.compiler }}-${{ matrix.build_type }}-${{ matrix.arch }}.zip
 
       - name: Clean up
         if: matrix.arch == 'x64' && startsWith(github.ref, 'refs/tags/')
         run: |
-          rm -rf out/linux/x64/tman-linux-${{ matrix.compiler }}-${{ matrix.build_type }}-${{ matrix.arch }}.zip
-          rm -rf out/linux/x64/ten_packages-linux-${{ matrix.compiler }}-${{ matrix.build_type }}-${{ matrix.arch }}.zip
+          rm -rf out/linux/${{ matrix.arch }}/tman-linux-${{ matrix.compiler }}-${{ matrix.build_type }}-${{ matrix.arch }}.zip
+          rm -rf out/linux/${{ matrix.arch }}/ten_packages-linux-${{ matrix.compiler }}-${{ matrix.build_type }}-${{ matrix.arch }}.zip
 
           df -h .
 
       - name: Publish release to TEN cloud store
         if: ${{ matrix.arch == 'x64' && startsWith(github.ref, 'refs/tags/') && matrix.compiler == 'gcc' && matrix.build_type == 'release' && matrix.arch == 'x64' }}
         run: |
-          TMAN_BIN=$(pwd)/out/linux/x64/ten_manager/bin/tman
+          TMAN_BIN=$(pwd)/out/linux/${{ matrix.arch }}/ten_manager/bin/tman
 
-          cd out/linux/x64
+          cd out/linux/${{ matrix.arch }}
           ARRAY=(
             "app/default_app_cpp"
             "app/default_app_go"
@@ -223,7 +213,7 @@ jobs:
       - name: Clean up
         if: ${{ matrix.arch == 'x64' && startsWith(github.ref, 'refs/tags/') && matrix.compiler == 'gcc' && matrix.build_type == 'release' && matrix.arch == 'x64' }}
         run: |
-          cd out/linux/x64
+          cd out/linux/${{ matrix.arch }}
           ARRAY=(
             "app/default_app_cpp"
             "app/default_app_go"
@@ -245,6 +235,66 @@ jobs:
 
           df -h .
 
+  test-standalone-linux-ubuntu2204:
+    needs: build-linux-intel-ubuntu2204
+    runs-on: ubuntu-latest
+    strategy:
+      matrix:
+        compiler: [gcc, clang]
+        build_type: [debug, release]
+        arch: [x64, x86]
+        include:
+          - compiler: gcc
+            build_type: debug
+            arch: x86
+        exclude:
+          - compiler: clang
+            arch: x86
+    container:
+      image: ghcr.io/ten-framework/ten_building_ubuntu2204
+    steps:
+      - name: Download build artifacts (tar archive)
+        uses: actions/download-artifact@v4
+        with:
+          name: tests-artifacts-${{ matrix.compiler }}-${{ matrix.build_type }}-${{ matrix.arch }}
+          path: out/linux/${{ matrix.arch }}
+
+      - name: Extract tests artifacts preserving permissions
+        run: |
+          tar -xzvf out/linux/${{ matrix.arch }}/tests-artifacts.tar.gz
+
+      - name: View folder structure content
+        run: |
+          df -h .
+          tree -L 6 -I ".*" .
+
+      - name: Set ulimit and sysctl
+        run: |
+          # Because there are concurrent test cases which involves many
+          # concurrent socket connections, we need to enlarge the maximum number
+          # of the opened file descriptor.
+          ulimit -n 102400
+
+          # Because there are concurrent test cases (in 'smoke' and
+          # 'integration') which will create many concurrent connections
+          # simutaneously, we increase the TCP listening backlog value to 8192.
+          sysctl -w net.core.somaxconn=8192
+        shell: bash
+
+      - uses: actions/setup-node@v4
+        with:
+          node-version: 20
+
+      - name: Update tman config.json
+        if: matrix.arch == 'x64'
+        run: |
+          CONFIG_FILE="out/linux/${{ matrix.arch }}/tests/local_registry/config.json"
+          echo "Before update:"
+          cat $CONFIG_FILE
+          sed -i "s|\(file://\)[^\"]*\(out\/linux\/${{ matrix.arch }}\/tests\/local_registry\)|\1${GITHUB_WORKSPACE}/\2|" $CONFIG_FILE
+          echo "After update:"
+          cat $CONFIG_FILE
+
       - name: Run Tests (ten_utils_unit_test)
         env:
           ASAN_OPTIONS: detect_leaks=1:detect_stack_use_after_return=1:color=always:unmap_shadow_on_exit=1:abort_on_error=1
@@ -252,14 +302,14 @@ jobs:
           TEN_ENABLE_MEMORY_TRACKING: "true"
           TEN_ENABLE_BACKTRACE_DUMP: "true"
         run: |
-          chmod +x out/linux/x64/tests/standalone/ten_utils_unit_test
-          out/linux/x64/tests/standalone/ten_utils_unit_test || { echo "test failed"; exit 1; }
+          chmod +x out/linux/${{ matrix.arch }}/tests/standalone/ten_utils_unit_test
+          out/linux/${{ matrix.arch }}/tests/standalone/ten_utils_unit_test || { echo "test failed"; exit 1; }
 
           df -h .
 
       - name: Clean up
         run: |
-          rm -rf out/linux/x64/tests/standalone/ten_utils_unit_test
+          rm -rf out/linux/${{ matrix.arch }}/tests/standalone/ten_utils_unit_test
 
           df -h .
 
@@ -270,32 +320,14 @@ jobs:
           TEN_ENABLE_MEMORY_TRACKING: "true"
           TEN_ENABLE_BACKTRACE_DUMP: "true"
         run: |
-          chmod +x out/linux/x64/tests/standalone/ten_runtime_unit_test
-          out/linux/x64/tests/standalone/ten_runtime_unit_test || { echo "test failed"; exit 1; }
+          chmod +x out/linux/${{ matrix.arch }}/tests/standalone/ten_runtime_unit_test
+          out/linux/${{ matrix.arch }}/tests/standalone/ten_runtime_unit_test || { echo "test failed"; exit 1; }
 
           df -h
 
       - name: Clean up
         run: |
-          rm -rf out/linux/x64/tests/standalone/ten_runtime_unit_test
-
-          df -h .
-
-      - name: Run Tests (ten_runtime_smoke_test)
-        env:
-          ASAN_OPTIONS: detect_leaks=1:detect_stack_use_after_return=1:color=always:unmap_shadow_on_exit=1:abort_on_error=1
-          MALLOC_CHECK_: 3
-          TEN_ENABLE_MEMORY_TRACKING: "true"
-          TEN_ENABLE_BACKTRACE_DUMP: "true"
-        run: |
-          chmod +x out/linux/x64/tests/standalone/ten_runtime_smoke_test
-          out/linux/x64/tests/standalone/ten_runtime_smoke_test || { echo "test failed"; exit 1; }
-
-          df -h .
-
-      - name: Clean up
-        run: |
-          rm -rf out/linux/x64/tests/standalone/ten_runtime_smoke_test
+          rm -rf out/linux/${{ matrix.arch }}/tests/standalone/ten_runtime_unit_test
 
           df -h .
 
@@ -307,7 +339,7 @@ jobs:
           TEN_ENABLE_MEMORY_TRACKING: "true"
           TEN_ENABLE_BACKTRACE_DUMP: "true"
         run: |
-          cd out/linux/x64/tests/standalone/ten_rust
+          cd out/linux/${{ matrix.arch }}/tests/standalone/ten_rust
 
           chmod +x unit_test
           chmod +x integration_test
@@ -320,7 +352,7 @@ jobs:
       - name: Clean up
         if: matrix.arch == 'x64'
         run: |
-          rm -rf out/linux/x64/tests/standalone/ten_rust
+          rm -rf out/linux/${{ matrix.arch }}/tests/standalone/ten_rust
 
           df -h .
 
@@ -332,20 +364,120 @@ jobs:
           TEN_ENABLE_MEMORY_TRACKING: "true"
           TEN_ENABLE_BACKTRACE_DUMP: "true"
         run: |
-          cd out/linux/x64/tests/standalone/ten_manager
+          cd out/linux/${{ matrix.arch }}/tests/standalone/ten_manager
 
           chmod +x unit_test
+          chmod +x integration_test
 
           ./unit_test || { echo "ten_manager unit test failed"; exit 1; }
+          ./integration_test || { echo "ten_manager integration test failed"; exit 1; }
 
           df -h .
 
       - name: Clean up
         if: matrix.arch == 'x64'
         run: |
-          rm -rf out/linux/x64/tests/standalone/ten_manager
+          rm -rf out/linux/${{ matrix.arch }}/tests/standalone/ten_manager
 
           df -h .
+
+      - name: Run Tests (ten_runtime_smoke_test)
+        env:
+          ASAN_OPTIONS: detect_leaks=1:detect_stack_use_after_return=1:color=always:unmap_shadow_on_exit=1:abort_on_error=1
+          MALLOC_CHECK_: 3
+          TEN_ENABLE_MEMORY_TRACKING: "true"
+          TEN_ENABLE_BACKTRACE_DUMP: "true"
+        run: |
+          chmod +x out/linux/${{ matrix.arch }}/tests/standalone/ten_runtime_smoke_test
+          out/linux/${{ matrix.arch }}/tests/standalone/ten_runtime_smoke_test || { echo "test failed"; exit 1; }
+
+          df -h .
+
+      - name: Clean up
+        run: |
+          rm -rf out/linux/${{ matrix.arch }}/tests/standalone/ten_runtime_smoke_test
+
+          df -h .
+
+  test-integration-linux-ubuntu2204:
+    needs: build-linux-intel-ubuntu2204
+    runs-on: ubuntu-latest
+    strategy:
+      matrix:
+        compiler: [gcc, clang]
+        build_type: [debug, release]
+        arch: [x64, x86]
+        include:
+          - compiler: gcc
+            build_type: debug
+            arch: x86
+        exclude:
+          - compiler: clang
+            arch: x86
+    container:
+      image: ghcr.io/ten-framework/ten_building_ubuntu2204
+    steps:
+      - uses: actions/checkout@v4
+        with:
+          fetch-depth: 0
+          submodules: false
+
+      - name: Trust working directory
+        run: git config --global --add safe.directory "${GITHUB_WORKSPACE}"
+
+      - name: Initialize and update submodules except docs/
+        run: |
+          # Retrieve all submodule paths, excluding `docs/`.
+          submodules=$(git config --file .gitmodules --get-regexp path | awk '$2 != "docs" { print $2 }')
+
+          git submodule init
+
+          for submodule in $submodules; do
+            echo "Initializing submodule: $submodule"
+            git submodule update --init --recursive "$submodule"
+          done
+
+      - name: Download build artifacts (tar archive)
+        uses: actions/download-artifact@v4
+        with:
+          name: tests-artifacts-${{ matrix.compiler }}-${{ matrix.build_type }}-${{ matrix.arch }}
+          path: out/linux/${{ matrix.arch }}
+
+      - name: Extract tests artifacts preserving permissions
+        run: |
+          tar -xzvf out/linux/${{ matrix.arch }}/tests-artifacts.tar.gz
+
+      - name: View folder structure content
+        run: |
+          df -h .
+          tree -L 6 -I ".*" .
+
+      - name: Set ulimit and sysctl
+        run: |
+          # Because there are concurrent test cases which involves many
+          # concurrent socket connections, we need to enlarge the maximum number
+          # of the opened file descriptor.
+          ulimit -n 102400
+
+          # Because there are concurrent test cases (in 'smoke' and
+          # 'integration') which will create many concurrent connections
+          # simutaneously, we increase the TCP listening backlog value to 8192.
+          sysctl -w net.core.somaxconn=8192
+        shell: bash
+
+      - uses: actions/setup-node@v4
+        with:
+          node-version: 20
+
+      - name: Update tman config.json
+        if: matrix.arch == 'x64'
+        run: |
+          CONFIG_FILE="out/linux/${{ matrix.arch }}/tests/local_registry/config.json"
+          echo "Before update:"
+          cat $CONFIG_FILE
+          sed -i "s|\(file://\)[^\"]*\(out\/linux\/${{ matrix.arch }}\/tests\/local_registry\)|\1${GITHUB_WORKSPACE}/\2|" $CONFIG_FILE
+          echo "After update:"
+          cat $CONFIG_FILE
 
       - name: Install Python dependencies via script
         run: |
@@ -361,7 +493,7 @@ jobs:
           TEN_ENABLE_MEMORY_TRACKING: "true"
           TEN_ENABLE_BACKTRACE_DUMP: "true"
         run: |
-          cd out/linux/x64/
+          cd out/linux/${{ matrix.arch }}/
           pytest -s tests/ten_manager/
 
           df -h .
@@ -369,7 +501,7 @@ jobs:
       - name: Clean up
         if: matrix.arch == 'x64'
         run: |
-          rm -rf out/linux/x64/tests/ten_manager
+          rm -rf out/linux/${{ matrix.arch }}/tests/ten_manager
 
           df -h .
 
@@ -404,7 +536,7 @@ jobs:
           df -h .
 
           export PATH=$(pwd)/core/ten_gn:$PATH
-          cd out/linux/x64/
+          cd out/linux/${{ matrix.arch }}/
           pytest -s tests/ten_runtime/integration/
 
           df -h .
