fix: refine codes

diff --git a/.github/workflows/build_mac_x64.yml b/.github/workflows/build_mac_x64.yml
--- a/.github/workflows/build_mac_x64.yml
+++ b/.github/workflows/build_mac_x64.yml
@@ -281,10 +281,13 @@ jobs:
           TEN_ENABLE_BACKTRACE_DUMP: "true"
         run: |
           cd out/mac/x64/tests/standalone/ten_rust
+
           chmod +x unit_test
           chmod +x integration_test
+
           ./unit_test || { echo "ten_rust unit test failed"; exit 1; }
           ./integration_test || { echo "ten_rust integration test failed"; exit 1; }
+
           df -h .
 
       - name: Run Tests (ten_manager standalone tests)
@@ -295,8 +298,13 @@ jobs:
           TEN_ENABLE_BACKTRACE_DUMP: "true"
         run: |
           cd out/mac/x64/tests/standalone/ten_manager
+
           chmod +x unit_test
+          chmod +x integration_test
+
           ./unit_test || { echo "ten_manager unit test failed"; exit 1; }
+          ./integration_test || { echo "ten_manager integration test failed"; exit 1; }
+
           df -h .
 
   test-integration:
diff --git a/.github/workflows/build_win.yml b/.github/workflows/build_win.yml
--- a/.github/workflows/build_win.yml
+++ b/.github/workflows/build_win.yml
@@ -246,16 +246,22 @@ jobs:
       - name: Run Tests (ten_rust standalone tests)
         run: |
           cd out/win/x64/tests/standalone/ten_rust
+
           chmod +x unit_test
           chmod +x integration_test
+
           ./unit_test || { echo "ten_rust unit test failed"; exit 1; }
           ./integration_test || { echo "ten_rust integration test failed"; exit 1; }
 
       - name: Run Tests (ten_manager standalone tests)
         run: |
           cd out/win/x64/tests/standalone/ten_manager
+
           chmod +x unit_test
+          chmod +x integration_test
+
           ./unit_test || { echo "ten_manager unit test failed"; exit 1; }
+          ./integration_test || { echo "ten_manager integration test failed"; exit 1; }
 
   test-integration:
     needs: build
