feat: clean up the pytest ci flow so that GitHub can launch pytest case (#365)
* feat: initial commit

* feat: open the integration tests under github CI

* feat: open the integration tests under github CI

* fix: lazy build for github CI

* feat: build integration test during testing

* fix: make pkg-run-root-dir not requeired

* fix: remove use_asan_lib_marker

* feat: assemble app during integration testing and cleanup after testing

* chore: test

* chore: test

* chore: fix CI workflow

* chore: fix CI workflow

* chore: fix CI workflow

* chore: disable a test

* chore: fix workflow

* fix: add cgo limiter for go apis

* chore: test

* chore: test

* fix: memory leak

* chore: test

* fix: refine codes

* fix: refine codes

* fix: refine codes

* fix: refine codes

* fix: refine codes

---------

Co-authored-by: Hu Yueh-Wei <wei.hu.tw@gmail.com>

diff --git a/.github/workflows/build_mac.yml b/.github/workflows/build_mac.yml
--- a/.github/workflows/build_mac.yml
+++ b/.github/workflows/build_mac.yml
@@ -76,7 +76,7 @@ jobs:
           fi
           export PATH=$(pwd)/core/ten_gn:$PATH
           echo $PATH
-          tgn gen mac arm64 ${{ matrix.build_type }} -- log_level=1 enable_serialized_actions=true ten_enable_integration_tests=false ten_enable_private_tests=false ten_rust_enable_gen_cargo_config=false ten_enable_cargo_clean=true
+          tgn gen mac arm64 ${{ matrix.build_type }} -- log_level=1 enable_serialized_actions=true ten_enable_private_tests=false ten_rust_enable_gen_cargo_config=false ten_enable_cargo_clean=true
           tgn build mac arm64 ${{ matrix.build_type }}
           tree -I 'gen|obj' out
 
@@ -220,7 +220,7 @@ jobs:
           fi
           export PATH=$(pwd)/core/ten_gn:$PATH
           echo $PATH
-          tgn gen mac x64 ${{ matrix.build_type }} -- log_level=1 enable_serialized_actions=true ten_enable_integration_tests=false ten_enable_private_tests=false ten_rust_enable_gen_cargo_config=false ten_enable_cargo_clean=true
+          tgn gen mac x64 ${{ matrix.build_type }} -- log_level=1 enable_serialized_actions=true ten_enable_private_tests=false ten_rust_enable_gen_cargo_config=false ten_enable_cargo_clean=true
           tgn build mac x64 ${{ matrix.build_type }}
           tree -I 'gen|obj' out
 
@@ -301,6 +301,17 @@ jobs:
           cd out/mac/x64/
           pytest -s tests/ten_manager/
 
+      - name: Run tests (ten_runtime integration tests)
+        env:
+          ASAN_OPTIONS: detect_stack_use_after_return=1:color=always:unmap_shadow_on_exit=1:abort_on_error=1
+          MALLOC_CHECK_: 3
+          TEN_ENABLE_MEMORY_TRACKING: "true"
+          TEN_ENABLE_BACKTRACE_DUMP: "true"
+        run: |
+          export PATH=$(pwd)/core/ten_gn:$PATH
+          cd out/mac/x64/
+          pytest -s tests/ten_runtime/integration/ || { echo "ten_runtime integration test failed"; exit 1; }
+
   # Building ten_runtime without the ten_rust library (i.e., ten_enable_ten_rust_apis=false).
   build-mac-arm64-without-ten-rust:
     concurrency:
@@ -365,7 +376,7 @@ jobs:
           fi
           export PATH=$(pwd)/core/ten_gn:$PATH
           echo $PATH
-          tgn gen mac arm64 ${{ matrix.build_type }} -- log_level=1 enable_serialized_actions=true ten_enable_integration_tests=false ten_enable_private_tests=false ten_rust_enable_gen_cargo_config=false ten_enable_ten_rust_apis=false
+          tgn gen mac arm64 ${{ matrix.build_type }} -- log_level=1 enable_serialized_actions=true ten_enable_private_tests=false ten_rust_enable_gen_cargo_config=false ten_enable_ten_rust_apis=false
           tgn build mac arm64 ${{ matrix.build_type }}
           tree -I 'gen|obj' out
 
