Revert "feat: in Python&Nodejs binding, modify the constructor of cmd_result …" (#750)
Co-authored-by: xxxxl_sun <31622273+sunxilin@users.noreply.github.com>
Co-authored-by: sunxilin <sunxilin@shengwang.cn>
Co-authored-by: sxl <sunxilin@agora.io>

diff --git a/.github/workflows/build_win.yml b/.github/workflows/build_win.yml
--- a/.github/workflows/build_win.yml
+++ b/.github/workflows/build_win.yml
@@ -1,4 +1,4 @@
-name: Windows
+name: Windows (x64)
 
 on:
   release:
@@ -19,7 +19,7 @@ concurrency:
   cancel-in-progress: true
 
 jobs:
-  win-x64:
+  build:
     runs-on: windows-latest
     env:
       PYTHONIOENCODING: utf-8
@@ -121,6 +121,107 @@ jobs:
             out/win/x64/tman-win-${{ matrix.build_type }}-x64.zip
             out/win/x64/ten_packages-win-${{ matrix.build_type }}-x64.zip
 
+      - name: Package tests relevant artifacts preserving permissions
+        shell: pwsh
+        run: |
+          $basePath = "out/win/x64"
+          $items = @("tests", "ten_manager", "tgn_args.txt")
+          $files = @()
+
+          foreach ($item in $items) {
+            $path = Join-Path $basePath $item
+            if (Test-Path $path) {
+              $files += $path
+            }
+          }
+
+          if ($files.Count -gt 0) {
+            Compress-Archive -Path $files -DestinationPath tests-artifacts.zip -Force
+          }
+
+      - name: Upload tests relevant artifacts
+        uses: actions/upload-artifact@v4
+        with:
+          name: tests-artifacts-${{ matrix.build_type }}
+          path: tests-artifacts.zip
+          if-no-files-found: ignore
+
+  test-standalone:
+    needs: build
+    runs-on: windows-latest
+    env:
+      PYTHONIOENCODING: utf-8
+    strategy:
+      matrix:
+        build_type: [debug, release]
+    steps:
+      - uses: actions/checkout@v4
+        with:
+          fetch-depth: 0
+          submodules: false
+
+      - name: Trust working directory
+        run: git config --global --add safe.directory "${GITHUB_WORKSPACE}"
+
+      - name: Initialize and update submodules except docs/
+        shell: bash
+        run: |
+          # Retrieve all submodule paths, excluding `docs/`.
+          submodules=$(git config --file .gitmodules --get-regexp path | awk '$2 != "docs" { print $2 }')
+          git submodule init
+          for submodule in $submodules; do
+            echo "Initializing submodule: $submodule"
+            git submodule update --init --recursive "$submodule"
+          done
+
+      - uses: actions/setup-node@v4
+        with:
+          node-version: 20
+
+      - uses: ilammy/msvc-dev-cmd@v1
+
+      - uses: actions/setup-python@v5
+        with:
+          python-version: "3.10"
+
+      - uses: actions/setup-go@v5
+        with:
+          go-version: "stable"
+          cache: false
+
+      - name: Install tools and dependencies
+        run: |
+          pip3 install --use-pep517 python-dotenv jinja2
+          go install golang.org/dl/go1.20.12@latest && go1.20.12 download
+          go env -w GOFLAGS="-buildvcs=false"
+          rustup default nightly
+          cargo install --force cbindgen
+
+      - name: Get Python executable path
+        run: |
+          $pythonPath = python -c "import sys; print(sys.executable)"
+          Write-Output "Python executable path: $pythonPath"
+          $pythonDir = Split-Path $pythonPath
+          Write-Output "Python directory path: $pythonDir"
+          echo "PYTHON3_PATH=$pythonDir" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
+        shell: pwsh
+
+      - name: Use Python path
+        run: |
+          Write-Output "The Python directory is located at: $env:PYTHON3_PATH"
+        shell: pwsh
+
+      - name: Download build artifacts
+        uses: actions/download-artifact@v4
+        with:
+          name: tests-artifacts-${{ matrix.build_type }}
+          path: out/win/x64
+
+      - name: Extract tests artifacts preserving permissions
+        shell: pwsh
+        run: |
+          Expand-Archive -Path "out/win/x64/tests-artifacts.zip" -DestinationPath "out/win/x64" -Force
+
       - name: Run Tests (ten_utils_unit_test)
         env:
           TEN_ENABLE_BACKTRACE_DUMP: "true"
@@ -157,8 +258,86 @@ jobs:
           cd out/win/x64/tests/standalone/ten_manager
 
           chmod +x unit_test
+          chmod +x integration_test
 
           ./unit_test || { echo "ten_manager unit test failed"; exit 1; }
+          ./integration_test || { echo "ten_manager integration test failed"; exit 1; }
+
+  test-integration:
+    needs: build
+    runs-on: windows-latest
+    env:
+      PYTHONIOENCODING: utf-8
+    strategy:
+      matrix:
+        build_type: [debug, release]
+    steps:
+      - uses: actions/checkout@v4
+        with:
+          fetch-depth: 0
+          submodules: false
+
+      - name: Trust working directory
+        run: git config --global --add safe.directory "${GITHUB_WORKSPACE}"
+
+      - name: Initialize and update submodules except docs/
+        shell: bash
+        run: |
+          # Retrieve all submodule paths, excluding `docs/`.
+          submodules=$(git config --file .gitmodules --get-regexp path | awk '$2 != "docs" { print $2 }')
+          git submodule init
+          for submodule in $submodules; do
+            echo "Initializing submodule: $submodule"
+            git submodule update --init --recursive "$submodule"
+          done
+
+      - uses: actions/setup-node@v4
+        with:
+          node-version: 20
+
+      - uses: ilammy/msvc-dev-cmd@v1
+
+      - uses: actions/setup-python@v5
+        with:
+          python-version: "3.10"
+
+      - uses: actions/setup-go@v5
+        with:
+          go-version: "stable"
+          cache: false
+
+      - name: Install tools and dependencies
+        run: |
+          pip3 install --use-pep517 python-dotenv jinja2
+          go install golang.org/dl/go1.20.12@latest && go1.20.12 download
+          go env -w GOFLAGS="-buildvcs=false"
+          rustup default nightly
+          cargo install --force cbindgen
+
+      - name: Get Python executable path
+        run: |
+          $pythonPath = python -c "import sys; print(sys.executable)"
+          Write-Output "Python executable path: $pythonPath"
+          $pythonDir = Split-Path $pythonPath
+          Write-Output "Python directory path: $pythonDir"
+          echo "PYTHON3_PATH=$pythonDir" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
+        shell: pwsh
+
+      - name: Use Python path
+        run: |
+          Write-Output "The Python directory is located at: $env:PYTHON3_PATH"
+        shell: pwsh
+
+      - name: Download build artifacts
+        uses: actions/download-artifact@v4
+        with:
+          name: tests-artifacts-${{ matrix.build_type }}
+          path: out/win/x64
+
+      - name: Extract tests artifacts preserving permissions
+        shell: pwsh
+        run: |
+          Expand-Archive -Path "out/win/x64/tests-artifacts.zip" -DestinationPath "out/win/x64" -Force
 
       - name: Install Python dependencies via script
         run: |
