feat: add ten_manager test cases

diff --git a/.github/workflows/build_linux_ubuntu1804.yml b/.github/workflows/build_linux_ubuntu1804.yml
--- a/.github/workflows/build_linux_ubuntu1804.yml
+++ b/.github/workflows/build_linux_ubuntu1804.yml
@@ -74,29 +74,15 @@ jobs:
           chmod +x out/linux/x64/tests/standalone/ten_runtime_unit_test
           out/linux/x64/tests/standalone/ten_runtime_unit_test || { echo "test failed"; exit 1; }
 
-      # - name: Run Tests (ten_runtime_smoke_test)
-      #   env:
-      #     ASAN_OPTIONS: detect_leaks=1:detect_stack_use_after_return=1:color=always:unmap_shadow_on_exit=1:abort_on_error=1
-      #     MALLOC_CHECK_: 3
-      #     TEN_ENABLE_MEMORY_TRACKING: "true"
-      #     TEN_ENABLE_BACKTRACE_DUMP: "true"
-      #   run: |
-      #     chmod +x out/linux/x64/tests/standalone/ten_runtime_smoke_test
-      #     out/linux/x64/tests/standalone/ten_runtime_smoke_test || { echo "test failed"; exit 1; }
-
-      - name: Set up Python
-        uses: actions/setup-python@v5
-        with:
-          python-version: "3.13"
-          cache: "pip"
-
-      - name: Install Python dependencies via script
+      - name: Run Tests (ten_runtime_smoke_test)
+        env:
+          ASAN_OPTIONS: detect_leaks=1:detect_stack_use_after_return=1:color=always:unmap_shadow_on_exit=1:abort_on_error=1
+          MALLOC_CHECK_: 3
+          TEN_ENABLE_MEMORY_TRACKING: "true"
+          TEN_ENABLE_BACKTRACE_DUMP: "true"
         run: |
-          python .github/tools/setup_pytest_dependencies.py
-
-      - name: Run Pytest
-        run: |
-          pytest -s tests/ten_manager/
+          chmod +x out/linux/x64/tests/standalone/ten_runtime_smoke_test
+          out/linux/x64/tests/standalone/ten_runtime_smoke_test || { echo "test failed"; exit 1; }
 
       - name: Upload ten_packages
         uses: actions/upload-artifact@v3
