feat: open the integration tests under github CI

diff --git a/.github/workflows/build_linux_ubuntu2204.yml b/.github/workflows/build_linux_ubuntu2204.yml
--- a/.github/workflows/build_linux_ubuntu2204.yml
+++ b/.github/workflows/build_linux_ubuntu2204.yml
@@ -126,6 +126,16 @@ jobs:
           cd out/linux/x64/
           pytest -s tests/ten_manager/
 
+      - name: Run tests (ten_runtime integration tests)
+        env:
+          ASAN_OPTIONS: detect_leaks=1:detect_stack_use_after_return=1:color=always:unmap_shadow_on_exit=1:abort_on_error=1
+          MALLOC_CHECK_: 3
+          TEN_ENABLE_MEMORY_TRACKING: "true"
+          TEN_ENABLE_BACKTRACE_DUMP: "true"
+        run: |
+          cd out/linux/x64/
+          pytest -s tests/ten_runtime/integration/ || { echo "ten_runtime integration test failed"; exit 1; }
+
       - name: Update supports before upload or publish
         run: |
           UPDATE_SUPPORTS_SCRIPT=$(pwd)/tools/supports/update_supports_in_manifest_json.py
