fix: refine codes

diff --git a/.github/workflows/linux_ubuntu2204.yml b/.github/workflows/linux_ubuntu2204.yml
--- a/.github/workflows/linux_ubuntu2204.yml
+++ b/.github/workflows/linux_ubuntu2204.yml
@@ -24,7 +24,7 @@ jobs:
     strategy:
       matrix:
         compiler: [gcc, clang]
-        build_type: [debug]
+        build_type: [debug, release]
         arch: [x64, x86]
         include:
           - compiler: gcc
@@ -240,7 +240,7 @@ jobs:
     strategy:
       matrix:
         compiler: [gcc, clang]
-        build_type: [debug]
+        build_type: [debug, release]
         arch: [x64, x86]
         include:
           - compiler: gcc
@@ -294,91 +294,91 @@ jobs:
           echo "After update:"
           cat $CONFIG_FILE
 
-      # - name: Run Tests (ten_utils_unit_test)
-      #   env:
-      #     ASAN_OPTIONS: detect_leaks=1:detect_stack_use_after_return=1:color=always:unmap_shadow_on_exit=1:abort_on_error=1
-      #     MALLOC_CHECK_: 3
-      #     TEN_ENABLE_MEMORY_TRACKING: "true"
-      #     TEN_ENABLE_BACKTRACE_DUMP: "true"
-      #   run: |
-      #     chmod +x out/linux/${{ matrix.arch }}/tests/standalone/ten_utils_unit_test
-      #     out/linux/${{ matrix.arch }}/tests/standalone/ten_utils_unit_test || { echo "test failed"; exit 1; }
+      - name: Run Tests (ten_utils_unit_test)
+        env:
+          ASAN_OPTIONS: detect_leaks=1:detect_stack_use_after_return=1:color=always:unmap_shadow_on_exit=1:abort_on_error=1
+          MALLOC_CHECK_: 3
+          TEN_ENABLE_MEMORY_TRACKING: "true"
+          TEN_ENABLE_BACKTRACE_DUMP: "true"
+        run: |
+          chmod +x out/linux/${{ matrix.arch }}/tests/standalone/ten_utils_unit_test
+          out/linux/${{ matrix.arch }}/tests/standalone/ten_utils_unit_test || { echo "test failed"; exit 1; }
 
-      #     df -h .
+          df -h .
 
-      # - name: Clean up
-      #   run: |
-      #     rm -rf out/linux/${{ matrix.arch }}/tests/standalone/ten_utils_unit_test
+      - name: Clean up
+        run: |
+          rm -rf out/linux/${{ matrix.arch }}/tests/standalone/ten_utils_unit_test
 
-      #     df -h .
+          df -h .
 
-      # - name: Run Tests (ten_runtime_unit_test)
-      #   env:
-      #     ASAN_OPTIONS: detect_leaks=1:detect_stack_use_after_return=1:color=always:unmap_shadow_on_exit=1:abort_on_error=1
-      #     MALLOC_CHECK_: 3
-      #     TEN_ENABLE_MEMORY_TRACKING: "true"
-      #     TEN_ENABLE_BACKTRACE_DUMP: "true"
-      #   run: |
-      #     chmod +x out/linux/${{ matrix.arch }}/tests/standalone/ten_runtime_unit_test
-      #     out/linux/${{ matrix.arch }}/tests/standalone/ten_runtime_unit_test || { echo "test failed"; exit 1; }
+      - name: Run Tests (ten_runtime_unit_test)
+        env:
+          ASAN_OPTIONS: detect_leaks=1:detect_stack_use_after_return=1:color=always:unmap_shadow_on_exit=1:abort_on_error=1
+          MALLOC_CHECK_: 3
+          TEN_ENABLE_MEMORY_TRACKING: "true"
+          TEN_ENABLE_BACKTRACE_DUMP: "true"
+        run: |
+          chmod +x out/linux/${{ matrix.arch }}/tests/standalone/ten_runtime_unit_test
+          out/linux/${{ matrix.arch }}/tests/standalone/ten_runtime_unit_test || { echo "test failed"; exit 1; }
 
-      #     df -h
+          df -h
 
-      # - name: Clean up
-      #   run: |
-      #     rm -rf out/linux/${{ matrix.arch }}/tests/standalone/ten_runtime_unit_test
+      - name: Clean up
+        run: |
+          rm -rf out/linux/${{ matrix.arch }}/tests/standalone/ten_runtime_unit_test
 
-      #     df -h .
+          df -h .
 
-      # - name: Run Tests (ten_rust standalone tests)
-      #   if: matrix.arch == 'x64'
-      #   env:
-      #     ASAN_OPTIONS: detect_leaks=1:detect_stack_use_after_return=1:color=always:unmap_shadow_on_exit=1:abort_on_error=1
-      #     MALLOC_CHECK_: 3
-      #     TEN_ENABLE_MEMORY_TRACKING: "true"
-      #     TEN_ENABLE_BACKTRACE_DUMP: "true"
-      #   run: |
-      #     cd out/linux/${{ matrix.arch }}/tests/standalone/ten_rust
+      - name: Run Tests (ten_rust standalone tests)
+        if: matrix.arch == 'x64'
+        env:
+          ASAN_OPTIONS: detect_leaks=1:detect_stack_use_after_return=1:color=always:unmap_shadow_on_exit=1:abort_on_error=1
+          MALLOC_CHECK_: 3
+          TEN_ENABLE_MEMORY_TRACKING: "true"
+          TEN_ENABLE_BACKTRACE_DUMP: "true"
+        run: |
+          cd out/linux/${{ matrix.arch }}/tests/standalone/ten_rust
 
-      #     chmod +x unit_test
-      #     chmod +x integration_test
+          chmod +x unit_test
+          chmod +x integration_test
 
-      #     ./unit_test || { echo "ten_rust unit test failed"; exit 1; }
-      #     ./integration_test || { echo "ten_rust integration test failed"; exit 1; }
+          ./unit_test || { echo "ten_rust unit test failed"; exit 1; }
+          ./integration_test || { echo "ten_rust integration test failed"; exit 1; }
 
-      #     df -h .
+          df -h .
 
-      # - name: Clean up
-      #   if: matrix.arch == 'x64'
-      #   run: |
-      #     rm -rf out/linux/${{ matrix.arch }}/tests/standalone/ten_rust
+      - name: Clean up
+        if: matrix.arch == 'x64'
+        run: |
+          rm -rf out/linux/${{ matrix.arch }}/tests/standalone/ten_rust
 
-      #     df -h .
+          df -h .
 
-      # - name: Run Tests (ten_manager standalone tests)
-      #   if: matrix.arch == 'x64'
-      #   env:
-      #     ASAN_OPTIONS: detect_leaks=1:detect_stack_use_after_return=1:color=always:unmap_shadow_on_exit=1:abort_on_error=1
-      #     MALLOC_CHECK_: 3
-      #     TEN_ENABLE_MEMORY_TRACKING: "true"
-      #     TEN_ENABLE_BACKTRACE_DUMP: "true"
-      #   run: |
-      #     cd out/linux/${{ matrix.arch }}/tests/standalone/ten_manager
+      - name: Run Tests (ten_manager standalone tests)
+        if: matrix.arch == 'x64'
+        env:
+          ASAN_OPTIONS: detect_leaks=1:detect_stack_use_after_return=1:color=always:unmap_shadow_on_exit=1:abort_on_error=1
+          MALLOC_CHECK_: 3
+          TEN_ENABLE_MEMORY_TRACKING: "true"
+          TEN_ENABLE_BACKTRACE_DUMP: "true"
+        run: |
+          cd out/linux/${{ matrix.arch }}/tests/standalone/ten_manager
 
-      #     chmod +x unit_test
-      #     chmod +x integration_test
+          chmod +x unit_test
+          chmod +x integration_test
 
-      #     ./unit_test || { echo "ten_manager unit test failed"; exit 1; }
-      #     ./integration_test || { echo "ten_manager integration test failed"; exit 1; }
+          ./unit_test || { echo "ten_manager unit test failed"; exit 1; }
+          ./integration_test || { echo "ten_manager integration test failed"; exit 1; }
 
-      #     df -h .
+          df -h .
 
-      # - name: Clean up
-      #   if: matrix.arch == 'x64'
-      #   run: |
-      #     rm -rf out/linux/${{ matrix.arch }}/tests/standalone/ten_manager
+      - name: Clean up
+        if: matrix.arch == 'x64'
+        run: |
+          rm -rf out/linux/${{ matrix.arch }}/tests/standalone/ten_manager
 
-      #     df -h .
+          df -h .
 
       - name: Run Tests (ten_runtime_smoke_test)
         env:
@@ -388,7 +388,7 @@ jobs:
           TEN_ENABLE_BACKTRACE_DUMP: "true"
         run: |
           chmod +x out/linux/${{ matrix.arch }}/tests/standalone/ten_runtime_smoke_test
-          out/linux/${{ matrix.arch }}/tests/standalone/ten_runtime_smoke_test --gtest_filter=ExtensionTest.FailedToConnectToRemote* || { echo "test failed"; exit 1; }
+          out/linux/${{ matrix.arch }}/tests/standalone/ten_runtime_smoke_test || { echo "test failed"; exit 1; }
 
           df -h .
 
diff --git a/.github/workflows/win.yml b/.github/workflows/win.yml
--- a/.github/workflows/win.yml
+++ b/.github/workflows/win.yml
@@ -25,7 +25,7 @@ jobs:
       PYTHONIOENCODING: utf-8
     strategy:
       matrix:
-        build_type: [debug]
+        build_type: [debug, release]
     steps:
       - uses: actions/checkout@v4
         with:
@@ -153,7 +153,7 @@ jobs:
       PYTHONIOENCODING: utf-8
     strategy:
       matrix:
-        build_type: [debug]
+        build_type: [debug, release]
     steps:
       - uses: actions/checkout@v4
         with:
@@ -222,50 +222,50 @@ jobs:
         run: |
           Expand-Archive -Path "out/win/x64/tests-artifacts.zip" -DestinationPath "out/win/x64" -Force
 
-      # - name: Run Tests (ten_utils_unit_test)
-      #   env:
-      #     TEN_ENABLE_BACKTRACE_DUMP: "true"
-      #   run: |
-      #     chmod +x out/win/x64/tests/standalone/ten_utils_unit_test
-      #     out/win/x64/tests/standalone/ten_utils_unit_test
+      - name: Run Tests (ten_utils_unit_test)
+        env:
+          TEN_ENABLE_BACKTRACE_DUMP: "true"
+        run: |
+          chmod +x out/win/x64/tests/standalone/ten_utils_unit_test
+          out/win/x64/tests/standalone/ten_utils_unit_test
 
-      # - name: Run Tests (ten_runtime_unit_test)
-      #   env:
-      #     TEN_ENABLE_BACKTRACE_DUMP: "true"
-      #   run: |
-      #     chmod +x out/win/x64/tests/standalone/ten_runtime_unit_test
-      #     out/win/x64/tests/standalone/ten_runtime_unit_test
+      - name: Run Tests (ten_runtime_unit_test)
+        env:
+          TEN_ENABLE_BACKTRACE_DUMP: "true"
+        run: |
+          chmod +x out/win/x64/tests/standalone/ten_runtime_unit_test
+          out/win/x64/tests/standalone/ten_runtime_unit_test
 
-      # - name: Run Tests (ten_rust standalone tests)
-      #   run: |
-      #     cd out/win/x64/tests/standalone/ten_rust
+      - name: Run Tests (ten_rust standalone tests)
+        run: |
+          cd out/win/x64/tests/standalone/ten_rust
 
-      #     chmod +x unit_test
-      #     chmod +x integration_test
+          chmod +x unit_test
+          chmod +x integration_test
 
-      #     ./unit_test || { echo "ten_rust unit test failed"; exit 1; }
-      #     ./integration_test || { echo "ten_rust integration test failed"; exit 1; }
+          ./unit_test || { echo "ten_rust unit test failed"; exit 1; }
+          ./integration_test || { echo "ten_rust integration test failed"; exit 1; }
 
-      # - name: Run Tests (ten_manager standalone tests)
-      #   run: |
-      #     cd out/win/x64/tests/standalone/ten_manager
+      - name: Run Tests (ten_manager standalone tests)
+        run: |
+          cd out/win/x64/tests/standalone/ten_manager
 
-      #     chmod +x unit_test
-      #     chmod +x integration_test
+          chmod +x unit_test
+          chmod +x integration_test
 
-      #     ./unit_test || { echo "ten_manager unit test failed"; exit 1; }
-      #     ./integration_test || { echo "ten_manager integration test failed"; exit 1; }
+          ./unit_test || { echo "ten_manager unit test failed"; exit 1; }
+          ./integration_test || { echo "ten_manager integration test failed"; exit 1; }
 
-      # #   continue-on-error: true
-      # # - name: Setup tmate session
-      # #   uses: mxschmitt/action-tmate@v3
+      #   continue-on-error: true
+      # - name: Setup tmate session
+      #   uses: mxschmitt/action-tmate@v3
 
       - name: Run Tests (ten_runtime_smoke_test)
         env:
           TEN_ENABLE_BACKTRACE_DUMP: "true"
         run: |
           chmod +x out/win/x64/tests/standalone/ten_runtime_smoke_test
-          out/win/x64/tests/standalone/ten_runtime_smoke_test --gtest_filter=ExtensionTest.FailedToConnectToRemote*
+          out/win/x64/tests/standalone/ten_runtime_smoke_test
 
   test-integration:
     needs: build
